package router

import "os"

const dnsmasqConfig = `# Auto-generated by Tainer — do not edit
# Resolve *.tainer.me to localhost for offline development
address=/tainer.me/127.0.0.1
# Forward all other queries to upstream DNS
server=8.8.8.8
server=8.8.4.4
`

func WriteDnsmasqConf(path string) error {
	return os.WriteFile(path, []byte(dnsmasqConfig), 0644)
}
