package router

import (
	"fmt"
	"os"
	"path/filepath"
)

// AddSSHPiperEntry creates a workingdir entry for sshpiper to route SSH by username.
func AddSSHPiperEntry(baseDir, projectName, projectIP, privateKeyPath string) error {
	projectDir := filepath.Join(baseDir, projectName)
	if err := os.MkdirAll(projectDir, 0755); err != nil {
		return fmt.Errorf("creating sshpiper dir: %w", err)
	}

	// sshpiper workingdir backend expects a sshpiper.yaml per user
	config := fmt.Sprintf(`# Auto-generated by Tainer — do not edit
username: %s
authorized_keys: authorized_keys
upstream:
  host: %s
  port: 22
  username: root
  identity: %s
`, projectName, projectIP, privateKeyPath)

	configPath := filepath.Join(projectDir, "sshpiper.yaml")
	if err := os.WriteFile(configPath, []byte(config), 0644); err != nil {
		return fmt.Errorf("writing sshpiper config: %w", err)
	}

	return nil
}

// RemoveSSHPiperEntry removes the workingdir entry for a project.
func RemoveSSHPiperEntry(baseDir, projectName string) {
	os.RemoveAll(filepath.Join(baseDir, projectName))
}
