#!/bin/bash

set -e

echo "/opt/tainer/bin" > /etc/paths.d/00-tainer

# make sure to ignore errors, this is not a hard requirement to use tainer
/opt/tainer/bin/tainer-mac-helper install || :

# Add pointer to tainer docs in manpath
mkdir -p /usr/local/etc/man.d/
echo "MANPATH /opt/tainer/docs/man" > /usr/local/etc/man.d/tainer.man.conf
