ARG PHP_VERSION=8.4
FROM php:${PHP_VERSION}-fpm-alpine

RUN apk add --no-cache libpng-dev libjpeg-turbo-dev libzip-dev libxml2-dev && \
    docker-php-ext-install mysqli pdo_mysql pdo_pgsql gd zip xml mbstring
