package env

import (
	"crypto/rand"
	"fmt"
	"math/big"
	"os"
	"strings"

	"github.com/cyber5-io/tainer/pkg/tainer/manifest"
)

const charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

func randomPassword(length int) string {
	b := make([]byte, length)
	for i := range b {
		n, _ := rand.Int(rand.Reader, big.NewInt(int64(len(charset))))
		b[i] = charset[n.Int64()]
	}
	return string(b)
}

// DBCreds carries the database identity a generated .env must agree with.
// At init time these are freshly minted; at start time they MUST be the
// pod's existing secrets — the database is already initialized with them,
// so writing anything else would hand the app credentials that don't work.
type DBCreds struct {
	Name         string
	User         string
	Password     string
	RootPassword string
}

// Generate creates a .env file for the project with freshly minted
// credentials. Init-time path: `tainer start` later adopts these same creds
// into the secrets store (pod.LoadOrCreateSecrets), keeping .env and the
// database in agreement. If the file already exists, it is not overwritten.
func Generate(m *manifest.Manifest, path string) error {
	return GenerateWithCreds(m, path, DBCreds{
		Name:         "tainer",
		User:         "tainer",
		Password:     randomPassword(32),
		RootPassword: randomPassword(32),
	})
}

// GenerateAppEnv creates the app-directory .env (html/.env for node apps)
// with ONLY database connection settings: DB_HOST/PORT/NAME/USER/PASSWORD and
// the DATABASE_URL/URI the app dials with. Deliberately excluded: the root
// password (the app never needs it and html/ is the most-exposed dir in the
// project), native DB-init vars (the db container reads those from injected
// env), and tainer metadata. Projects without a database get no file at all.
// Never overwrites an existing file.
func GenerateAppEnv(m *manifest.Manifest, path string, creds DBCreds) error {
	if !m.HasDatabase() {
		return nil
	}
	if _, err := os.Stat(path); err == nil {
		return nil // file exists, skip
	}

	scheme := "mysql"
	if m.Runtime.Database == manifest.DatabasePostgres {
		scheme = "postgresql"
	}
	url := fmt.Sprintf("%s://%s:%s@127.0.0.1:%s/%s",
		scheme, creds.User, creds.Password, m.DBPort(), creds.Name)

	lines := []string{
		"# Database connection (generated by tainer from this pod's credentials)",
		"DB_HOST=127.0.0.1",
		fmt.Sprintf("DB_PORT=%s", m.DBPort()),
		fmt.Sprintf("DB_NAME=%s", creds.Name),
		fmt.Sprintf("DB_USER=%s", creds.User),
		fmt.Sprintf("DB_PASSWORD=%s", creds.Password),
		fmt.Sprintf("DATABASE_URL=%s", url),
	}
	if m.Project.Type == manifest.TypeKompozi {
		// PayloadCMS dials DATABASE_URI.
		lines = append(lines, fmt.Sprintf("DATABASE_URI=%s", url))
	}

	return os.WriteFile(path, []byte(strings.Join(lines, "\n")+"\n"), 0644)
}

// GenerateWithCreds creates a .env file for the project using the given DB
// credentials. Start-time path (clone-then-start): a fresh clone has no .env
// (it's gitignored), so pod start regenerates it from the pod's effective
// secrets — same values the database container is initialized with. If the
// file already exists, it is never overwritten (the user owns it).
func GenerateWithCreds(m *manifest.Manifest, path string, creds DBCreds) error {
	if _, err := os.Stat(path); err == nil {
		return nil // file exists, skip
	}

	var lines []string

	lines = append(lines,
		"# Tainer",
		fmt.Sprintf("TAINER_DOMAIN=%s", m.Project.Domain),
	)

	if m.HasDatabase() {
		lines = append(lines,
			"# Database (generic)",
			"DB_HOST=127.0.0.1",
			fmt.Sprintf("DB_PORT=%s", m.DBPort()),
			fmt.Sprintf("DB_NAME=%s", creds.Name),
			fmt.Sprintf("DB_USER=%s", creds.User),
			fmt.Sprintf("DB_PASSWORD=%s", creds.Password),
			fmt.Sprintf("DB_ROOT_PASSWORD=%s", creds.RootPassword),
		)

		// Native env vars for DB container initialization
		if m.Runtime.Database == manifest.DatabaseMariaDB {
			lines = append(lines,
				"",
				"# MariaDB native vars",
				fmt.Sprintf("MYSQL_DATABASE=%s", creds.Name),
				fmt.Sprintf("MYSQL_USER=%s", creds.User),
				fmt.Sprintf("MYSQL_PASSWORD=%s", creds.Password),
				fmt.Sprintf("MYSQL_ROOT_PASSWORD=%s", creds.RootPassword),
			)
		} else if m.Runtime.Database == manifest.DatabasePostgres {
			lines = append(lines,
				"",
				"# PostgreSQL native vars",
				fmt.Sprintf("POSTGRES_DB=%s", creds.Name),
				fmt.Sprintf("POSTGRES_USER=%s", creds.User),
				fmt.Sprintf("POSTGRES_PASSWORD=%s", creds.Password),
			)
		}

		if m.IsNode() {
			var scheme string
			if m.Runtime.Database == manifest.DatabasePostgres {
				scheme = "postgresql"
			} else {
				scheme = "mysql"
			}
			lines = append(lines,
				"",
				fmt.Sprintf("DATABASE_URL=%s://%s:%s@127.0.0.1:%s/%s",
					scheme, creds.User, creds.Password, m.DBPort(), creds.Name),
			)
		}
	}

	if m.Project.Type == manifest.TypeWordPress {
		lines = append(lines,
			"",
			"# WordPress",
			"WP_DEBUG=true",
			fmt.Sprintf("WP_HOME=https://%s", m.Project.Domain),
			fmt.Sprintf("WP_SITEURL=https://%s", m.Project.Domain),
		)
	}

	if m.Project.Type == manifest.TypeKompozi {
		payloadSecret := randomPassword(48)
		lines = append(lines,
			"",
			"# Kompozi / PayloadCMS",
			fmt.Sprintf("PAYLOAD_SECRET=%s", payloadSecret),
			"KOMPOZI_ADMIN_EMAIL=tainer@tainer.me",
			"KOMPOZI_ADMIN_PASSWORD=tainer",
		)
		// PayloadCMS reads DATABASE_URI — alias of DATABASE_URL.
		if m.HasDatabase() {
			lines = append(lines,
				fmt.Sprintf("DATABASE_URI=postgresql://%s:%s@127.0.0.1:%s/%s",
					creds.User, creds.Password, m.DBPort(), creds.Name),
			)
		}
	}

	content := strings.Join(lines, "\n") + "\n"
	return os.WriteFile(path, []byte(content), 0644)
}
